// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZR7pZJ0aIR2V8rCv6xzDoVN1z6rLJSo',
    appId: '1:620734943822:web:d7923c6588d154ac20a91f',
    messagingSenderId: '620734943822',
    projectId: 'eyego-task-3f12d',
    authDomain: 'eyego-task-3f12d.firebaseapp.com',
    storageBucket: 'eyego-task-3f12d.firebasestorage.app',
    measurementId: 'G-JCJQ72KCQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfRFr7saPZgvxaCigJ9YYgpYr_BOhETOM',
    appId: '1:620734943822:android:6c0a042de211e92720a91f',
    messagingSenderId: '620734943822',
    projectId: 'eyego-task-3f12d',
    storageBucket: 'eyego-task-3f12d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegM4AQzDbeNN4fTUDmJZXY08XpjO6-9I',
    appId: '1:620734943822:ios:acd4875705b5e01220a91f',
    messagingSenderId: '620734943822',
    projectId: 'eyego-task-3f12d',
    storageBucket: 'eyego-task-3f12d.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegM4AQzDbeNN4fTUDmJZXY08XpjO6-9I',
    appId: '1:620734943822:ios:acd4875705b5e01220a91f',
    messagingSenderId: '620734943822',
    projectId: 'eyego-task-3f12d',
    storageBucket: 'eyego-task-3f12d.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ZR7pZJ0aIR2V8rCv6xzDoVN1z6rLJSo',
    appId: '1:620734943822:web:c1f4d3ccd1c980eb20a91f',
    messagingSenderId: '620734943822',
    projectId: 'eyego-task-3f12d',
    authDomain: 'eyego-task-3f12d.firebaseapp.com',
    storageBucket: 'eyego-task-3f12d.firebasestorage.app',
    measurementId: 'G-PJZJK4RKDX',
  );
}
